### ISSUE TITLE
broken example

### ISSUE THREAD

**Issue by Gargo** [VamshiIITBHU14/PeekAndPopExtension#2]
Open the details view and look at the top of the picture - it is hidden behind a navigation bar

**Comment by VamshiIITBHU14** [comment]
Hey Gargo! That's because the Content Mode of that UIImageView is set to AspectFill. You can change it to AspectFit or ScaleToFill as per your requirements.

**Comment by Gargo** [comment]
@VamshiIITBHU14 thanks for fast reply
